Core MVC Project 6/Core MVC Project 6/Models/Food.cs
using System.ComponentModel.DataAnnotations;

namespace Core_MVC_Project_6.Models
{
	public class Food
	{
		[Key]
        public int FoodID { get; set; }

        [Required(ErrorMessage = "This area should not empty")]
        public string FoodName { get; set; }

        [Required(ErrorMessage = "This area should not empty")]
        public string FoodDescription { get; set;}

        [Required(ErrorMessage = "This area should not empty")]
        public int FoodPrice { get; set; }

        [Required(ErrorMessage = "This area should not empty")]
        public string FoodImageURL { get; set; }

        [Required(ErrorMessage = "This area should not empty")]
        public int FoodStock { get; set; }
        public int CategoryID { get; set; }
        public bool Status { get; set; }
        public virtual Category Category { get; set; }
    }
}

Core MVC Project 6/Core MVC Project 6/Controllers/FoodController.cs
using Microsoft.AspNetCore.Mvc;
using Core_MVC_Project_6.Repositeries;
using Core_MVC_Project_6.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using X.PagedList;
using Microsoft.AspNetCore.Authorization;

namespace Core_MVC_Project_6.Controllers
{
	[Authorize]
	public class FoodController : Controller
	{
        FoodRepositeries fRepo = new FoodRepositeries();
		CategoryRepositeries cRepo = new CategoryRepositeries();
        public IActionResult Index(int page = 1)
		{
			var foods = fRepo.TList("Category").ToPagedList(page, 3);
			return View(foods);
		}

		public IActionResult DeleteFood(int id)
		{
			var food = fRepo.GetT(id);
			fRepo.DeleteT(food);

			return RedirectToAction("Index");
		}

		[HttpGet]
		public IActionResult UpdateFood(int id)
		{
			var food = fRepo.GetT(id);
            List<SelectListItem> FoodsCategories = (from x in cRepo.TList()
                                                    select new SelectListItem
                                                    {
                                                        Text = x.CategoryName,
                                                        Value = x.CategoryID.ToString()
                                                    }).ToList();

            ViewBag.foodsCategories = FoodsCategories;
            return View(food);
		}

		[HttpPost]
		public IActionResult UpdateFood(Food f) 
		{
			fRepo.UpdateT(f);
			return RedirectToAction("Index");
		}

		[HttpGet]
		public IActionResult AddFood()
		{
			List<SelectListItem> FoodsCategories = (from x in cRepo.TList()
													select new SelectListItem
													{
														Text = x.CategoryName,
														Value = x.CategoryID.ToString()
													}).ToList();

			ViewBag.foodsCategories = FoodsCategories;

			return View();
		}

		[HttpPost]
		public IActionResult AddFood(Food f)
		{
			fRepo.AddT(f);

			return RedirectToAction("Index");
		}

		public IActionResult ActivationFood(int id)
		{
			var food = fRepo.GetT(id);
			if(food.Status)
			{
				food.Status = false;
			}

			else
			{
				food.Status = true;
			}
			fRepo.UpdateT(food);
			return RedirectToAction("Index");
		}

	}
}

Core MVC Project 6/Core MVC Project 6/Views/Food/AddFood.cshtml
@model Core_MVC_Project_6.Models.Food

@{
    ViewData["Title"] = "AddFood";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

@using (Html.BeginForm("AddFood", "Food", FormMethod.Post))
{
    <br />
    <h3>Food Name</h3>
    @Html.TextBoxFor(m => m.FoodName, new { @class="form-control"})
    
    <h3>Food Discription</h3>
    @Html.TextBoxFor(m => m.FoodDescription, new { @class="form-control"})
    <h3>Food Price</h3>
    @Html.TextBoxFor(m => m.FoodPrice, new { @class="form-control"})
    <h3>Food Stock</h3>
    @Html.TextBoxFor(m => m.FoodStock, new { @class="form-control"})
    <h3>Food Image</h3>
    @Html.TextBoxFor(m => m.FoodImageURL, new { @class="form-control"})
    <h3>Food Category</h3>
    @Html.DropDownListFor(m => m.CategoryID,(List<SelectListItem>)ViewBag.foodsCategories, new { @class="form-control"})

    <br />
    <button style="margin-left:10px;" class="btn btn-info">Add</button>
}

Core MVC Project 6/Core MVC Project 6/Views/Food/Index.cshtml
@using Core_MVC_Project_6.Models;
@using X.PagedList;
@using X.PagedList.Mvc.Core;
@model IPagedList<Food>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<br />
<table class="table table-bordered table-hover">
    <thead>
        <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Discription</th>
            <th>Category</th>
            <th>Price</th>
            <th>Stock</th>
            <th>Is Active</th>
            <th>Activate</th>
            <th>Update</th>
            <th>Delete</th>
        </tr>
    </thead>
    <tbody>
        @foreach(var f in Model)
        {
            <tr>
                <th>@f.FoodID</th>
                <td>@f.FoodName</td>
                <td>@f.FoodDescription</td>
                <td>@f.Category.CategoryName</td>
                <td>@f.FoodPrice</td>
                <td>@f.FoodStock</td>
                <td>@f.Status</td>
                <td><a href="/Food/ActivationFood/@f.FoodID" class="btn btn-default" style="background-color:cyan">Activate</a></td>
                <td><a href="/Food/UpdateFood/@f.FoodID" class="btn btn-success">Update</a></td>
                <td><a href="/Food/DeleteFood/@f.FoodID" class="btn btn-danger">Delete</a></td>
            </tr>
        }
    </tbody>
</table>
<br />
@Html.PagedListPager((IPagedList)Model, page => Url.Action("Index",new {page}))
<br />

<a href="/Food/AddFood" style="background-color:blueviolet; margin-left:10px;" class="btn btn-default">Add New Food</a>

Core MVC Project 6/Core MVC Project 6/Views/Food/UpdateFood.cshtml
@model Core_MVC_Project_6.Models.Food

@{
    ViewData["Title"] = "UpdateFood";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

@using (Html.BeginForm("UpdateFood", "Food", FormMethod.Post))
{
    <br />
    <h3>Food ID</h3>
    @Html.TextBoxFor(m => m.FoodID)
    ;
    <h3>Food Name</h3>
    @Html.TextBoxFor(m => m.FoodName, new { @class="form-control"})
    
    <h3>Category Description</h3>
    @Html.TextBoxFor(m => m.FoodDescription, new { @class="form-control"})
    <h3>Food Price</h3>
    @Html.TextBoxFor(m => m.FoodPrice, new { @class="form-control"})
    <h3>Food Image</h3>
    @Html.TextBoxFor(m => m.FoodImageURL, new { @class="form-control"})
    <h3>Food Stock</h3>
    @Html.TextBoxFor(m => m.FoodStock, new { @class="form-control"})
    <h3>Food Category</h3>
    @Html.DropDownListFor(m => m.CategoryID,(List<SelectListItem>)ViewBag.foodsCategories, new { @class="form-control"})
    <br />
    <button class="btn btn-default" style="background-color:aquamarine; margin-left:10px;">Save Changes</button>
}