Core MVC Project 6/Core MVC Project 6/Controllers/GraphController.cs
using Microsoft.AspNetCore.Mvc;
using Core_MVC_Project_6.Data;
using Core_MVC_Project_6.Models;

namespace Core_MVC_Project_6.Controllers
{
    public class GraphController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult VisualizeProductResult()
        {
            return Json(ProductList());
        }

        public List<Product> ProductList()
        {
            List<Product> products = new List<Product>();

            using (var pros = new Context())
            {
                products = pros.Foods.Select(x => new Product
                {
                    foodname = x.FoodName,
                    foodstock = x.FoodStock
                }).ToList();
            }

            return products;
        }

    }
}

Core MVC Project 6/Core MVC Project 6/Views/Graph/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<head>
    <meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests">
    <title>Result Visualization</title>
    <script type="text/javascript" src="https://www.google.com/jsapi"></script>
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script>
        $(document).ready(function () {
            $.ajax({
                type: "POST",
                dataType: "json",
                contentType: "application/json",
                url: '@Url.Action("VisualizeProductResult", "Graph")',
                success: function (result) {
                    google.charts.load('current', {
                        'packages': ['corechart']
                    });
                    google.charts.setOnLoadCallback(function () {
                        drawChart(result);
                    });
                }
            });
        });

        function drawChart(result) {
            var data = new google.visualization.DataTable();
            data.addColumn('string', 'Name');
            data.addColumn('number', 'Stoklar');
            var dataArray = [];

            $.each(result, function (i, obj) {
                dataArray.push([obj.foodname, obj.foodstock);
            });
            data.addRows(dataArray);

            var columnChartOptions = {
                title: "Ürün - Stok Grafiği",
                width: 1000,
                height: 400,
                bar: { groupWidth: "20%" },
            };

            var columnChart = new google.visualization.PieChart(document
                .getElementById('Piechart_div'));

            columnChart.draw(data, columnChartOptions);
        }
    </script>
</head>
<body>
    <div id="Piechart_div"></div>
</body>